language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  - "pip install . --use-mirrors"
  - "pip install pytest>=2.4.2 -U --use-mirrors"
  - "pip install pytest-cov pytest-pep8 mock coveralls --use-mirrors"
script: "py.test"
after_success:
  coveralls
branches:
  only:
    - master
    - develop
