language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "pypy"
install:
  - "pip install ."
  - "pip install pytest>=2.4.2 -U"
  - "pip install pytest-cov pytest-pep8 mock coveralls"
script: "py.test"
after_success:
  coveralls
branches:
  only:
    - master
    - develop
